
image: hashicorp/terraform:latest
pipelines:
    default:
        - step:
            script:
                - terraform init -backend-config="bucket=$AWS_S3_STATE_BUCKET"
                - terraform validate
                - terraform plan
    branches:
        master:        
            - step:
                deployment: "Development"
                script:
                    - terraform init -backend-config="bucket=$AWS_S3_STATE_BUCKET"                  
                    - terraform plan
                    - terraform apply -input=false -auto-approve