
image: hashicorp/terraform:latest
pipelines:     
    branches:
        master:        
            - step:
                deployment: "Development"
                script:
                    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                    - terraform init -backend-config="bucket=${AWS_S3_STATE_BUCKET}"                  
                    - terraform plan
                    - terraform apply -input=false -auto-approve